# render.yaml
services:
  - type: web
    name: chile-urbano-app
    env: node
    plan: free
    branch: main
    # Si tu package.json está en la raíz, no necesitas rootDirectory.
    # rootDirectory: .

    buildCommand: npm install
    startCommand: node src/app.js

    envVars:
      - key: MONGO_URI
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DISCORD_CALLBACK_URL
        sync: false
      - key: DISCORD_TARGET_GUILD_ID
        sync: false
      - key: DISCORD_ADMIN_ROLE_IDS
        sync: false
      - key: DISCORD_ADMIN_USER_IDS
        sync: false
      - key: DISCORD_BOT_TOKEN          # Agrega esta línea si usas el token del bot en la app
        sync: false

    # Render asigna automáticamente el puerto con process.env.PORT, no es necesario especificarlo
